ignition-devs/incendium

.gitmodules
.pre-commit-config.yaml

Add [Ignition-jython](https://github.com/thecesrom/Ignition/tree/jython) as submodule.

Add Ignition-jython submodule

---

src/incendium/user.py

this function extends `system.user.getUsers` allowing filtering by role

feat: add `get_users` function

---

.github/workflows/ci.yml

this will run when commits are pushed to `code` and `project` branches
and on pull_requests against the `code` branch

ci: update `ci.yml`

---

.github/workflows/ci.yml

- restrict to `code` branch for `push`
- add `PYTHON_VERSION` environment variable

refactor(ci): update `ci.yml`

---

.github/workflows/ci.yml

Signed-off-by: César Román <thecesrom@gmail.com>

fix(ci): run `ci` on all PRs

---

src/incendium/dataset.py

In `to_xml` we convert the dataset into a PyDataSet.
It is not necessary to turn the dataset into a PyDataSet.

refactor(dataset): use Dataset instance functions

---

.github/workflows/ci.yml
.pylintrc
.sourcery.yaml
pyproject.toml
src/incendium/dataset.py
src/incendium/date.py
src/incendium/db.py
src/incendium/exceptions.py
src/incendium/net.py
src/incendium/tag.py
src/incendium/types.py
src/incendium/user.py
src/incendium/util.py
src/incendium/vision/gui.py
src/incendium/vision/nav.py

The project does not currently have type hints.
This PR adds type hints, supporting classes, and changes to CI so we can run `mypy` and `ignition-api-stubs` against the code.

feat: add type hints

---

src/incendium/exceptions.py
src/incendium/helper/types.py

We get a warning when we catch a Python exception.
Issue Number: #65
This PR attempts to "cast our net" to also include Python exceptions, an not only Java exceptions.

fix(exceptions): fix inner_exception warning

---

src/incendium/dataset.py
src/incendium/db.py
src/incendium/exceptions.py
src/incendium/helper/types.py

Issue Number: #64
Allow `unicode` strings for `name_or_index`.

fix(db): accept unicode type for [In|Out]Param

---

src/incendium/date.py

We currently don't have functions to get the first and last day of the month for a given Date.
This PR adds those functions.

feat(date): add functions to get first and last day of the month

---

src/incendium/db.py

If the user wants to `print` `InParam` or `OutParam` to console, they would get the following output:
```python
>>> import system.db
>>> from incendium.db import InParam
>>> in_param = InParam("id", system.db.INTEGER, 42)
>>> print in_param
<incendium.db.InParam object at 0x00000000040900C8>
>>> repr(in_param)
'<incendium.db.InParam object at 0x00000000040900C8>'
```
With this PR, `Param` and its child classes will print "meaningful" information.
```python
>>> import system.db
>>> from incendium.db import InParam
>>> in_param = InParam("id", system.db.INTEGER, 42)
>>> print in_param
'id', 4, 42
>>> repr(in_param)
"InParam(name_or_index='id', type_code=4, value=42)" …
```

feat(db): add repr and str functions to Param

---

src/incendium/exceptions.py

`__repr__` and `__str__` produce better output.

refactor(exceptions): improve repr and str functions

---

src/incendium/db.py

The `o_get_data` docstring is incorrect.
This PR fixes the problem.

fix(db): fix o_get_data docstring

---

.flake8
.pylintrc
pyproject.toml
src/incendium/constants.py
src/incendium/dataset.py
src/incendium/db.py
src/incendium/exceptions.py
src/incendium/tag.py
src/incendium/user.py
src/incendium/util.py
src/incendium/vision/gui.py

PEP8 strict style
Embrace _pure_ **black**

style: use pure black

---

src/incendium/db.py

The value returned by `DisposableConnection`'s `status` property does not cast the result to `str`.
The value is now cast into `str`.

refactor(db): cast return value to str

---

.flake8
.pylintrc
.sourcery.yaml
ignition/script-python/incendium/constants/code.py
ignition/script-python/incendium/constants/resource.json
ignition/script-python/incendium/dataset/code.py
ignition/script-python/incendium/dataset/resource.json
ignition/script-python/incendium/db/code.py
ignition/script-python/incendium/db/resource.json
ignition/script-python/incendium/exceptions/code.py
ignition/script-python/incendium/exceptions/resource.json
ignition/script-python/incendium/net/code.py
ignition/script-python/incendium/net/resource.json
ignition/script-python/incendium/tag/code.py
ignition/script-python/incendium/tag/resource.json
ignition/script-python/incendium/user/code.py
ignition/script-python/incendium/user/resource.json
ignition/script-python/incendium/util/code.py
ignition/script-python/incendium/util/resource.json
ignition/script-python/incendium/vision/gui/code.py
ignition/script-python/incendium/vision/gui/resource.json
pyproject.toml

style: use pure black style

---

ignition/script-python/incendium/db/code.py
ignition/script-python/incendium/db/resource.json

refactor(db): return BasicDataset on _execute_sp result_set

---

.github/workflows/pylint.yml

Bump versions for `actions/setup-python` from 2 to 4, and `actions/checkout` from 2 to 3.
Set Python version as an env variable.

ci(gh): bump actions versions

---

.github/pull_request_template.md
.wakatime-project
CONTRIBUTING.md

Update CONTRIBUTING guidelines

docs: update CONTRIBUTING

---

.github/workflows/ci.yml
requirements.ci.txt
requirements.txt
tox.ini

We currently only run `pylint` and `mypy` on our CI workflow.
We will test installation on Python 2.7, and `pylint` and `mypy` on Python 3.10.

ci(github): use tox for running CI tests

---

.github/workflows/ci.yml
.pylintrc

We are running `tox` as a module, very verbose.
Run `tox` as an executable without verbosity.

ci(github): update CI workflow

---

.cz.toml
.cz.yaml

Use `.cz.yaml` for `commitizen`

chore(deps): move cz config

---

.cz.yaml
pyproject.toml
requirements.test.txt
requirements.txt
tox.ini

move commitizen config to its own file
create requirements file for testing this project
simplify requirements file
update tox.ini

chore: clean pyproject.toml

---

.github/workflows/ci.yml
tox.ini

We only run `pylint` with `tox`.
We will run `pre-commit` plust `pylint` with `tox`.

test: run pre-commit using tox

---

.sourcery.yaml
src/incendium/dataset.py
src/incendium/db.py
src/incendium/exceptions.py
src/incendium/user.py
tox.ini

We are not calling `super()` in base classes.
We are calling `super()` from base classes.
update sourcery configuration file
add strictness to mypy check
<https://eugeneyan.com/writing/uncommon-python/#using-super-in-base-classes>

refactor: add call to super in base classes

---

.github/workflows/ci.yml
.pylintrc
.sourcery.yaml
CONTRIBUTING.md
tox.ini

We use Python 3.10 for running our tests.
We will use Python 3.11.

ci: use Python 3.11

---

tox.ini

We will add an additional environment called `stubgen`; this will allow us to generate `incendium-stubs` on our dev env.

chore(tox): add stubgen additional environment

---

tox.ini

In 77df031 we introduced the `base` section and we are using it on `typecheck` and `stubgen`.
We will reference `base` on `lint` env.

chore(tox): update lint env

---

.github/workflows/ci.yml
.github/workflows/pypi_upload.yml
tox.ini

ci: cache Python version

---

requirements/lint.txt
requirements/style.txt
tox.ini

add style env
rename test.txt to lint.txt and replace tox with pylint normalize option names using snake_case

 test(tox): update configuration

---

.github/workflows/ci.yml

We are using `pre-commit` and `pylint` configuration files along with `tox`'s.
Use only `tox.ini` for hashFiles.

ci: update tox cache key

---

.github/workflows/ci.yml
.github/workflows/pypi_upload.yml

We are using alternate restore keys for our caches.
Force an exact match by remove restore keys.

ci: remove alternate restore keys

---

tox.ini

`tox` version is being suggested by `min_version`.
We will use `requires = tox>=4` to future-proof our tests.

test(tox): require tox >= 4

---

.github/dependabot.yml
.github/workflows/main.yml
.github/workflows/publish.yml

We are using https://github.com/thecesrom/workflows/tree/v0.0.2
We will use https://github.com/thecesrom/workflows/tree/v0.0.4
remove dependabot.yml

ci: use thecesrom/workflows@v0.0.4

---

.github/workflows/main.yml
.github/workflows/publish.yml

Use [`thecesrom/workflows@v1.0.0`]
[`thecesrom/workflows@v1.0.0`]: https://github.com/thecesrom/workflows/tree/v1.0.0

ci: use thecesrom/workflows v1.0.0

---

.pre-commit-config.yaml
src/incendium/db.py
src/incendium/net.py
src/incendium/user.py
src/incendium/util.py
src/incendium/vision/nav.py

update:
- black 23.1.0 → 23.3.0
- commitizen v2.42.0 → v2.42.1
remove:
- check-jsonschema

build(deps): add ssort v0.11.6

---

src/incendium/dataset.py

Add `incendium.dataset.from_list_of_dicts`.

feat(dataset): add from_list_of_dicts

---

src/incendium/db.py
src/incendium/helper/types.py

`SProcResult` is found in `helper.types`
Move `SProcResult` to `db` module and rename it to `_SProcResult`.

refactor(helper): move SProcResult from helper.types to db module

---

.pre-commit-config.yaml
setup.cfg
src/incendium/db.py
tox.ini

We did not have a mechanism for handling concurrent database connections using `DisposableConnection`.
Issue Number: #12
With the addition of `system.util.globals` in Ignition 8.1, it is possible to keep track of all active connections.

feat(db): handle concurrent DisposableConnection connections

---

.pre-commit-config.yaml
setup.py
src/incendium/__init__.py

update:
- docformatter: v1.5.1 → v1.6.3
- commitizen: v2.42.1 → 3.1.0

build(deps): bump dependencies

---

.pre-commit-config.yaml

update:
- docformatter: v1.6.3 to v1.6.4
- commitizen: 3.1.0 to 3.2.0

build(deps): bump versions

---

.github/workflows/main.yml
.github/workflows/publish.yml

ci: use coatl-dev/workflows@v3.0.0

---

.pre-commit-config.yaml

update:
- docformatter: v1.6.4 to v1.6.5
- commitizen: 3.2.0 to 3.2.1

build(deps): bump deps

---

.pre-commit-config.yaml

update:
- commitizen: 3.2.1 to 3.2.2

build(deps): bump commitizen to 3.2.2

---

.github/workflows/main.yml
.github/workflows/publish.yml

use:
- coatl-dev/workflows@v5.1.1
- coatl-dev/action-pypi-upload

ci: update CI/CD workflows

---

.cz.toml
.cz.yaml
.github/workflows/ci.yml
.github/workflows/pr-build.yml
.github/workflows/pre-commit-autoupdate.yml
.github/workflows/publish.yml
.sourcery.yaml

- use coatl-dev/workflows@v1
- add coatl-dev/action-pre-commit-autoupdate
- use TOML config for commitizen

ci: refactor-CI/CD)

---

.github/workflows/ci.yml
.github/workflows/pip-compile-upgrade.yml
.github/workflows/pr-build.yml
.github/workflows/pre-commit-autoupdate.yml
.github/workflows/publish.yml
README.md
tox.ini

ci: use coatl-dev/workflows@v3
